### ISSUE TITLE
Player Master

### ISSUE THREAD

**Issue by Noah4ever** [DerTyp187/defrain#8]
- [x] Player Join/Leave
- [x] Health
- [x] Get Player list
- [x] Player Death
- [x] Player Kill
- [x] Player Class
  - [x] Health (Updated from GameManager/PlayerMaster)
- [ ] Player Status (Dead/Alive)- List

**Comment by DerTyp187** [comment]
https://github.com/DerTyp187/defrain/commit/469fd047bd19b1c178b46eedc9f85a369348064f


HEALTH
 - Set Health of a player
 - Subtract Health from a player
 - Add Health to a player

DEAD (Just the Structure)
 - Player Dies
 - Another Player gets a kill

**Comment by DerTyp187** [comment]
GameManager Issue behandelt nun den PlayerMaster & GameMaster

**Comment by DerTyp187** [comment]
GameManager Issue behandelt nun den PlayerMaster & GameMaster
